# Generated by Django 3.2.11 on 2022-04-22 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='publisher',
            new_name='publishers',
        ),
        migrations.AddField(
            model_name='content',
            name='description',
            field=models.TextField(default='Udating'),
        ),
        migrations.AlterField(
            model_name='content',
            name='categories',
            field=models.ManyToManyField(related_name='contents', to='homepage.Category'),
        ),
    ]
